### PR TITLE
Config refactoring

### LINKED ISSUE #101: Fix and refactor configuration loading
bug: env vars overrides works only when viper default values are specified

reproduction steps:

- remove default value for `instance.local.service_mode`
- do not have `service_mode` in aem.yml : instance/local/service_mode
- run AEM CLI with `AEM_INSTANCE_LOCAL_SERVICE_MODE=true aem instance await` - not that bundles check is active but it should not
- put `service_mode` in aem.yml
- run again AEM CLI command, bundles check is skipped as desired

in general it means that to make config overriddable via env vars ALL possible default values need to be defined but they are not currently

TODO:

- define all default values for all possible config keys
- make somehow config values overridable (refactor viper config initialization or sth) even if there are no default values defined for all keys

### PR DESCRIPTION
**Pull request by krystian-panek-wttech**
fixes #101

### CODE REVIEW

File: pkg/base/base.go [hunk 1]
```diff
@@ -9,20 +9,12 @@ type Opts struct {
 	TmpDir string
 }
 
-func NewOpts() *Opts {
+func NewOpts(config *cfg.Config) *Opts {
 	return &Opts{
-		TmpDir: "aem/home/tmp",
+		TmpDir: config.Values().GetString("base.tmp_dir"),
```
Comment (krystian-panek-wttech) [inline pkg/base/base.go:14]: all config opts values to be rewritten in that way

File: cmd/aem/instance.go [hunk 2]
```diff
@@ -272,9 +272,10 @@ func (c *CLI) instanceAwaitCmd() *cobra.Command {
 			c.Ok("instance(s) awaited")
 		},
 	}
-	cmd.Flags().IntVar(&(c.config.Values().Instance.Check.DoneThreshold),
-		"done-threshold", c.config.Values().Instance.Check.DoneThreshold,
-		"Number of successful checks indicating done")
+	// TODO fix this
```
Comment (krystian-panek-wttech) [inline cmd/aem/instance.go:275]: only thing left

File: pkg/instance_manager_check.go [hunk 3]
```diff
@@ -155,7 +162,7 @@ func (im *InstanceManager) AwaitStopped(instances []Instance) error {
 	}
 	log.Infof(InstanceMsg(instances, "awaiting stopped"))
 	return im.CheckUntilDone(instances, im.CheckOpts, []Checker{
-		im.CheckOpts.AwaitStoppedTimeout,
+		im.CheckOpts.StopTimer,
```
Comment (krystian-panek-wttech) [inline pkg/instance_manager_check.go:165]: Align naming
