### PR TITLE
Windows / aem as background process fix

### LINKED ISSUE #79: Recompile CBP or look for alternative
image
even if that error is printed to the console, the AEM boots as expected
however it would be nice to mitigate that error and use one of techniques listed here:

https://serverfault.com/questions/9038/run-a-bat-file-in-a-scheduled-task-without-a-window

maybe as a first shot try this - https://serverfault.com/a/9039

### PR DESCRIPTION
**Pull request by krystian-panek-wttech**
Windows / Classic fix; fixes #79

### CODE REVIEW

File: pkg/instance/constants.go [hunk 1]
```diff
@@ -38,6 +40,8 @@ var OakRunSetPassword string
 type Role string
 
 const (
+	CbpExecutableFilename = "cbpow.exe"
```
Comment (krystian-panek-wttech) [inline pkg/instance/constants.go:43]: fixes #79

File: pkg/project/classic/dispatcher/Dockerfile [hunk 2]
```diff
@@ -6,7 +6,7 @@ RUN yum -y install httpd wget mod_ssl
 
 # Download & install dispatcher module
 RUN mkdir -p /tmp/dispatcher && cd /tmp/dispatcher && \
-    wget https://download.macromedia.com/dispatcher/download/dispatcher-apache2.4-linux-aarch64-${DISPATCHER_VERSION}.tar.gz -O dispatcher.tar.gz && \
+    wget https://download.macromedia.com/dispatcher/download/dispatcher-apache2.4-linux-$(uname -m)-${DISPATCHER_VERSION}.tar.gz -O dispatcher.tar.gz && \
```
Comment (krystian-panek-wttech) [inline pkg/project/classic/dispatcher/Dockerfile:9]: this is crazy - @tomasz-sobczyk-wttech take a look ;)

on Windows we had here x86_64; on M1 Mac aarch;

Docker is not isolating arch ;)

File: pkg/instance/constants.go [hunk 3]
```diff
@@ -29,7 +29,9 @@ func ProcessingModes() []string {
 	return []string{ProcessingAuto, ProcessingParallel, ProcessingSerial}
 }
 
-//go:embed resource/cbp.exe
+// CbpExecutable is a recompiled binary from code at 'https://ritchielawrence.github.io/cmdow' to avoid false-positive antivirus detection
+//
+//go:embed resource/cbpow.exe
```
Comment (krystian-panek-wttech) [inline pkg/instance/constants.go:34]: @maciej-majchrzak-wttech @tomasz-sobczyk-wttech have you been aware of it ?:D 

I am tricking anti-virus to run cmd in the background... I needed to recompile binary to avoid false-positive Nod32 reports
